version: '3.7'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydb}
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
